engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
    - "**.md"
    - "**.css"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.ts"
exclude_paths:
  - dist/
  - test/
  - typings/
  - docs/