engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
  eslint:
    enabled: true
    exclude_fingerprints:
      - 69d66db7a1141f5d1df9602e11f72895
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
    - "**.css"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.ts"
exclude_paths:
  - test/
  - typings/
  - docs/