sudo: false
language: node_js
node_js:
- '5'
- '6'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    code_climate:
      repo_token: e12fd8e03896426373067dfb39b00e2f36f3dccb4436fea8c8991107918724fc
deploy:
  api_key:
    secure: NpOwVo4xiaEsHlw21wHxNHPOEtEvRicwhdoKh84VBNlxc4+1H6EEIuWZwLw1dj6znpbPNXu3SC7c/PsnIUpqAQaSR+V9hMWL8lhSghTSqHhLrWKRVdtReO9i74mli03ICsCtvc6UBq92alJ9Hkwkb4BF0tUCcv6Nc1SOEb+ZtU8v5yL1P6iV5/03DTTsLyVhhFEyGP15jre08hUEFo1uMA41pdJxyAgLAZtK/kOk0pNkWNIqDH4IbyQkIDmh04naKYfweA3KzcWJiqqXheuIKFp01h9OykMtXxVBGpTTQt0Y4zcGWGKUvrsGeIosFSSK7DlEt5y5nOw43HG5PbVHjDB2OO8AjSmdCjk8qTynpUVUdAOy0LqzfV4n7SUvxOvcgY21XuJUnsFkfGspchJ7PRQhpLyDbWh7r+oweCxJD+WiEVe4hyftEdFMdsM9oCEYAqsdwFHSN5JV9P7EXtPvlBtN8OeeU1vmmHLKVDwLp/YoJ5djl6PFlEMieAqgtOC0Dd7Mji485vpSGfu8RJV/bLU+kfs9taA/5GRAo89YUiBmXQ0xRC7LkXF1Y0oEDIslMDuZVadpokxsfER4rQjhWpPZPKRUZMw0NwvE6UR94sp3sNdscEjS+MWoR4Ro7L0in06bfoaYN4/w6t+YVBNIdwrk4ktlvijCfqYExHC5a+A=
  email: bdfoster89@gmail.com
  provider: npm
